### ISSUE TITLE
Mock http fails after first message

### ISSUE THREAD

**Issue by manuranga** [ballerina-guides/enterprise-integration-patterns#18]
Http mock only works for a single message, from the second message onward it give an error `error: Http header does not exist`.

**Comment by manuranga** [comment]
Looks like this is a http2 related issue. Maybe getting a http2 specific header instead "Host" will solve the issue.
Lets try "AUTHORITY" and ":authority" headers.

**Comment by DimuthuMadushan** [comment]
`AUTHORITY` and `:authority` headers are not available in the request. @TharmiganK is there any workaround for this?

**Comment by TharmiganK** [comment]
> Http mock only works for a single message, from the second message onward it give an error `error: Http header does not exist`.

This is expected since the first request is an HTTP/2 Upgrade request which contains the `host` header. And the subsequent requests are made as HTTP/2 requests where we set the `:authority` header instead of the `host` header.

> `AUTHORITY` and `:authority` headers are not available in the request. @TharmiganK is there any workaround for this?

The headers are present in the request but we have not exposed the pseudo headers via the request object. @DimuthuMadushan can you create an issue for this? We will check if we can expose it via the request object

**Comment by DimuthuMadushan** [comment]
Created an issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4732

**Comment by DimuthuMadushan** [comment]
This is fixed with `ballerina 2201.8.0`.  Hence closed the issue.

**Comment by manuranga** [comment]
Can't close until we fix it in mock http app.

**Comment by DimuthuMadushan** [comment]
We don't have to fix anything in the mock server. As per https://github.com/ballerina-platform/module-ballerina-http/pull/1745, it will expose the HTTP2 pseudo headers and will map them to the relevant HTTP normal headers.

**Comment by manuranga** [comment]
Ahh great. thanks.
